import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
const canvas=document.querySelector('#game'),R=new THREE.WebGLRenderer({canvas,antialias:true});R.setPixelRatio(Math.min(devicePixelRatio,1.5));R.shadowMap.enabled=true;const S=new THREE.Scene();S.background=new THREE.Color(0x07101a);S.fog=new THREE.FogExp2(0x08101a,.0045);const C=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,1000),clock=new THREE.Clock();
S.add(new THREE.HemisphereLight(0x9db8ff,0x102015,1.7));const sun=new THREE.DirectionalLight(0xffffff,2.1);sun.position.set(-100,160,80);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);S.add(sun);
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.12}),world=new THREE.Group();S.add(world);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(700,700),mat(0x26302b));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;world.add(ground);
function road(x,z,w,d){const m=new THREE.Mesh(new THREE.BoxGeometry(w,.06,d),mat(0x15191e));m.position.set(x,.025,z);m.receiveShadow=true;world.add(m)}
for(let x=-300;x<=300;x+=60)road(x,0,20,700);for(let z=-300;z<=300;z+=60)road(0,z,700,20);
for(let x=-300;x<=300;x+=60)for(let z=-300;z<=300;z+=60){if(Math.random()<.22)continue;const w=34+Math.random()*14,d=34+Math.random()*14,h=8+Math.random()*35,b=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat([0x25303a,0x30343c,0x222e2a,0x38302c][Math.random()*4|0]));b.position.set(x+(Math.random()-.5)*6,h/2,z+(Math.random()-.5)*6);b.castShadow=true;b.userData.obstacle=true;world.add(b)}
const water=new THREE.Mesh(new THREE.PlaneGeometry(700,700),new THREE.MeshStandardMaterial({color:0x073c59,roughness:.28,metalness:.25,transparent:true,opacity:.9}));water.rotation.x=-Math.PI/2;water.position.y=-.03;world.add(water);
function car(col,police=false){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(2.5,.65,4.6),mat(col));body.position.y=.62;body.castShadow=true;g.add(body);const cab=new THREE.Mesh(new THREE.BoxGeometry(1.8,.62,2.1),mat(police?0x10151c:0x17202a));cab.position.y=1.08;g.add(cab);for(const x of[-.9,.9])for(const z of[-1.45,1.45]){const w=new THREE.Mesh(new THREE.CylinderGeometry(.38,.38,.32,14),mat(0x08090a));w.rotation.z=Math.PI/2;w.position.set(x,.35,z);g.add(w)}if(police){const bar=new THREE.Mesh(new THREE.BoxGeometry(1.2,.15,.4),mat(0x242832));bar.position.y=1.57;g.add(bar);for(const[x,c]of[[-.38,0x3377ff],[.38,0xff3344]]){const l=new THREE.PointLight(c,4,10);l.position.set(x,1.7,0);g.add(l)}}return g}
const player=car(0xdde5ee);player.position.set(0,.06,240);player.rotation.y=Math.PI;S.add(player);const cops=[];function addCop(i){const p=car(0x12161d,true);p.position.set((Math.random()-.5)*12,.06,player.position.z+45+i*18);p.userData={speed:12+Math.random()*4,ram:Math.random()<.75};S.add(p);cops.push(p)}for(let i=0;i<3;i++)addCop(i);
const cashPickups=[];for(let i=0;i<180;i++){const c=new THREE.Mesh(new THREE.CylinderGeometry(.55,.55,.18,14),mat(0xffca32));c.rotation.x=Math.PI/2;const lane=[-180,-120,-60,0,60,120,180][Math.random()*7|0],along=-260+Math.random()*520;c.position.set(Math.random()<.5?lane:along,.35,Math.random()<.5?along:lane);S.add(c);cashPickups.push(c)}
const state={run:false,cash:+localStorage.rogueCash||0,score:0,health:100,heat:1,dist:0,engine:+localStorage.engine||0,armour:+localStorage.armour||0,tyres:+localStorage.tyres||0,nitro:+localStorage.nitro||0,boostUntil:+localStorage.rogueBoostUntil||0,triple:false,revived:false};const input={l:false,r:false};
for(const id of['left','right']){const b=document.getElementById(id);b.onpointerdown=e=>{e.preventDefault();input[id==='left'?'l':'r']=true};b.onpointerup=b.onpointercancel=()=>input[id==='left'?'l':'r']=false;b.onpointerleave=()=>input[id==='left'?'l':'r']=false}
addEventListener('keydown',e=>{if(e.key.toLowerCase()==='a'||e.key==='ArrowLeft')input.l=true;if(e.key.toLowerCase()==='d'||e.key==='ArrowRight')input.r=true});addEventListener('keyup',e=>{if(e.key.toLowerCase()==='a'||e.key==='ArrowLeft')input.l=false;if(e.key.toLowerCase()==='d'||e.key==='ArrowRight')input.r=false});
let speed=0;function UI(){cash.textContent=Math.floor(state.cash);score.textContent=Math.floor(state.score);heat.textContent=Math.min(5,Math.floor(state.heat/20)+1);speedValue.textContent=Math.round(Math.abs(speed)*4.2);healthFill.style.width=Math.max(0,state.health)+'%';garageCash.textContent=Math.floor(state.cash);const left=Math.max(0,state.boostUntil-Date.now());boostStatus.classList.toggle('hidden',left<=0);boostTimer.textContent=left>0?` ${Math.ceil(left/1000)}s`:''}
function reset(){state.score=0;state.health=100+state.armour*14;state.heat=1;state.dist=0;state.triple=false;state.revived=false;speed=0;player.position.set(0,.06,240);player.rotation.y=Math.PI;cops.forEach((p,i)=>{p.position.set((Math.random()-.5)*12,.06,player.position.z+50+i*20);p.userData.speed=12+Math.random()*4});cashPickups.forEach(c=>c.visible=true);UI()}
function start(){reset();state.run=true;menu.classList.add('hidden');gameOver.classList.add('hidden');touch.classList.remove('hidden')}
function finish(){if(!state.run)return;state.run=false;touch.classList.add('hidden');const base=Math.max(50,state.score/30|0),payout=state.triple?base*3:base;state.cash+=payout;localStorage.rogueCash=state.cash;runSummary.innerHTML=`SCORE <b>${state.score|0}</b><br>DISTANCE ${state.dist|0}m<br>CASH EARNED <b>$${payout}</b>`;tripleRunBtn.classList.remove('hidden');reviveBtn.classList.remove('hidden');gameOver.classList.remove('hidden');UI();window.dispatchEvent(new CustomEvent('rogue:gameover'))}
function crashDamage(amount){state.health-=amount;speed*=.82;if(state.health<=0)finish()}
function update(dt){if(!state.run)return;const reverse=input.l&&input.r,steer=reverse?0:(input.r?1:input.l?-1:0),direction=reverse?-1:1,target=reverse?10:31+state.engine*2.5;speed=Math.min(target,speed+(reverse?18:12)*dt);if(!reverse)speed=Math.max(9,speed);else speed=Math.max(3,speed);player.rotation.y+=steer*(1.65+state.tyres*.12)*dt;const old=player.position.clone();player.position.x+=Math.sin(player.rotation.y)*-speed*direction*dt;player.position.z+=Math.cos(player.rotation.y)*-speed*direction*dt;
const onRoad=Math.abs(Math.round(player.position.x/60)*60-player.position.x)<11||Math.abs(Math.round(player.position.z/60)*60-player.position.z)<11;const inCity=Math.abs(player.position.x)<310&&Math.abs(player.position.z)<310;if(!inCity||!onRoad){state.health-=55*dt;if(state.health<=0){state.health=0;finish();return}}
for(const o of world.children)if(o.userData?.obstacle){const hw=o.geometry.parameters.width/2,hd=o.geometry.parameters.depth/2;if(Math.abs(player.position.x-o.position.x)<hw+1.15&&Math.abs(player.position.z-o.position.z)<hd+2.1){player.position.copy(old);speed*=.7;state.score=Math.max(0,state.score-3)}}
state.dist+=speed*dt;state.score+=speed*dt*2;state.heat=Math.min(100,state.heat+speed*dt*.022);const multiplier=Date.now()<state.boostUntil?2:1;for(const c of cashPickups)if(c.visible&&c.position.distanceTo(player.position)<2.5){c.visible=false;state.cash+=50*multiplier;state.score+=250*multiplier}
for(const p of cops){const dx=player.position.x-p.position.x,dz=player.position.z-p.position.z,d=Math.hypot(dx,dz),desired=Math.atan2(dx,dz);let diff=Math.atan2(Math.sin(desired-p.rotation.y),Math.cos(desired-p.rotation.y));p.rotation.y+=diff*Math.min(1,2*dt);let sp=p.userData.speed+Math.min(10,state.heat*.09);if(p.userData.ram&&d<22)sp+=10;p.position.x+=Math.sin(p.rotation.y)*-sp*dt;p.position.z+=Math.cos(p.rotation.y)*-sp*dt;if(d<3.7){crashDamage((p.userData.ram?36:20)*dt);p.position.x+=(player.position.x-p.position.x)*.1;p.position.z+=(player.position.z-p.position.z)*.1}if(p.position.z>player.position.z+55)p.position.z=player.position.z-90-Math.random()*80}
if(state.heat>25&&cops.length<5)addCop(cops.length);if(state.heat>55&&cops.length<7)addCop(cops.length);UI();const targetCam=player.position.clone().add(new THREE.Vector3(0,115,78));C.position.lerp(targetCam,.1);C.lookAt(player.position.x,0,player.position.z-10)}
function loop(){requestAnimationFrame(loop);update(Math.min(.04,clock.getDelta()));R.render(S,C)}loop();
startBtn.onclick=start;againBtn.onclick=start;menuBtn.onclick=()=>{gameOver.classList.add('hidden');menu.classList.remove('hidden')};garageBtn.onclick=()=>{menu.classList.add('hidden');garage.classList.remove('hidden');UI()};closeGarage.onclick=()=>{garage.classList.add('hidden');menu.classList.remove('hidden')};carsBtn.onclick=()=>{menu.classList.add('hidden');cars.classList.remove('hidden');renderCars()};closeCars.onclick=()=>{cars.classList.add('hidden');menu.classList.remove('hidden')};adShopBtn.onclick=()=>{menu.classList.add('hidden');adShop.classList.remove('hidden');UI()};closeAdShop.onclick=()=>{adShop.classList.add('hidden');menu.classList.remove('hidden')};
const carDefs=[['Rogue Runner',0,31,1,'STARTER'],['Shadow GT',2500,36,1.2,'FAST'],['Interceptor',6000,40,1.45,'RAMMER'],['Phantom X',12000,44,1.7,'ELITE']];let selected=localStorage.rogueCar||'Rogue Runner';function renderCars(){carList.innerHTML=carDefs.map(([name,cost,spd,hp,tag])=>`<div class="carCard"><div><b>${name}</b><small>${tag} · ${spd} SPEED · ${hp}x ARMOUR</small></div><button data-car="${name}" data-cost="${cost}">${selected===name?'EQUIPPED':cost===0?'FREE':`$${cost}`}</button></div>`).join('');document.querySelectorAll('[data-car]').forEach(b=>b.onclick=()=>{const name=b.dataset.car,cost=+b.dataset.cost;if(selected===name)return;if(state.cash>=cost){state.cash-=cost;selected=name;localStorage.rogueCash=state.cash;localStorage.rogueCar=name;renderCars();UI()}})}
document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{const t=b.dataset.upgrade,c={engine:500,armour:400,tyres:350,nitro:450}[t];if(state.cash>=c&&state[t]<5){state.cash-=c;state[t]++;localStorage.rogueCash=state.cash;localStorage[t]=state[t];UI()}});
addEventListener('resize',()=>{C.aspect=innerWidth/innerHeight;C.updateProjectionMatrix();R.setSize(innerWidth,innerHeight,false)});R.setSize(innerWidth,innerHeight,false);UI();renderCars();